require "pohoda/version"
require "pohoda/utils"
require "pohoda/base_element"
require "pohoda/invoice"
require "pohoda/type_currency_home"
require "pohoda/type_currency_foreign"
require "pohoda/number"
require "pohoda/payment_type"
require "pohoda/account"
require "pohoda/accounting"
require "pohoda/classification_vat"
require "pohoda/type_currency_home_item"
require "pohoda/type_currency_foreign_item"
require "pohoda/invoice_item"
require "pohoda/my_identity"
require "pohoda/partner_identity"
require "pohoda/blank_xml"
require "pohoda/my_address"
require "pohoda/reference"
require "pohoda/establishment"
require "pohoda/external_reference"
require "pohoda/address"
require "pohoda/shipping_to_address"
require "pohoda/payment_account"

module Pohoda
end
